plugins {
    id 'com.android.application'
}

android {
    namespace 'com.trilautanemas.tleschedule'
    compileSdk 35

    defaultConfig {
        applicationId 'com.trilautanemas.tleschedule'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.browser:browser:1.8.0'
}
